title: 'HSNPipeline'
description: 'A pipeline for processing and analyzing single-neuron data from human subjects.'

remote_theme: hydecorp/hydejack

author:
  social:
    github: HSNPipeline

menu:
  - title:  Home
    url:    /
  - title:  Templates
    url:    /templates/
  - title:  Sorting
    url:    /sorting/
  - title:  Converting
    url:    /converting/
  - title:  Analysis
    url:    /analysis/
  - title:  CodeMap
    url:    /codemap/
  - title:  Projects
    url:    /projects/
  - title:  hsntools
    url:    /hsntools
  - title:  spiketools
    url:    /spiketools
